---

- src: https://github.com/playingfield/ansible_role_web.git
  name: webserver
- src: dockpack.base_amq
- src: dockpack.base_postgres
- src: dockpack.base_utils
- src: dockpack.base_gcc
- src: dockpack.base_java8
- src: dockpack.base_maven
